import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { useState } from "react"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../ui/accordion"
import { Alert, AlertDescription, AlertTitle } from "../ui/alert"
import { Input } from "../ui/input"
import { Separator } from "../ui/separator"
import { Textarea } from "../ui/textarea"
import { TypographyInlineCode } from "../ui/typography"

const CYKAlgorithmTool = () => {
  const [grammar, setGrammar] = useState<{ input: string; output: string }[]>(
    []
  )
  const [startSymbol, setStartSymbol] = useState<string>("S")
  const [terminals, setTerminals] = useState<string[]>([])
  const [nonTerminals, setNonTerminals] = useState<string[]>([])
  const [string, setString] = useState<string>("")
  const [step, setStep] = useState(0)

  const [result, setResult] = useState<string | null>(null)

  const handleGrammarChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const lines = e.target.value.split("\n")
    const newGrammar: { input: string; output: string }[] = []
    lines.forEach((line) => {
      if (!line.includes("->")) {
        return
      }

      const [input, output] = line.split("->").map((part) => part.trim())

      output
        .split("|")
        .map((part) => part.trim())
        .forEach((o) => {
          newGrammar.push({ input, output: o })
        })
    })

    setGrammar(newGrammar)

    const newTerminals = new Set<string>()
    const newNonTerminals = new Set<string>()

    newGrammar.forEach(({ input, output }) => {
      newNonTerminals.add(input)
      output.split("").forEach((symbol) => {
        if (symbol.match(/^[a-z]$/)) {
          newTerminals.add(symbol)
        } else if (symbol.match(/^[A-Z]$/)) {
          newNonTerminals.add(symbol)
        }
      })
    })

    setTerminals(Array.from(newTerminals).sort((a, b) => a.localeCompare(b)))
    setNonTerminals(
      Array.from(newNonTerminals).sort((a, b) => a.localeCompare(b))
    )
  }

  return (
    <div>
      <Field>
        <FieldLabel htmlFor="input-string">String</FieldLabel>
        <Input
          id="input-string"
          placeholder="aabbbb"
          value={string}
          onChange={(e) => setString(e.target.value)}
        />
        <FieldDescription>
          The string you would like to check if it can be generated by the
          grammar
        </FieldDescription>
      </Field>

      <Field className="mt-4">
        <FieldLabel htmlFor="input-grammar">Production Rules</FieldLabel>
        <Textarea
          id="input-grammar"
          placeholder="S -> a | AB"
          onChange={(e) => handleGrammarChange(e)}
        />
        <FieldDescription>
          List all production rules of the grammar in CNF form:{" "}
          <TypographyInlineCode className="text-xs">
            A -&gt; a | AB
          </TypographyInlineCode>
        </FieldDescription>
      </Field>

      <Field className="mt-4">
        <FieldLabel htmlFor="input-starting">Starting Symbols</FieldLabel>
        <Input
          id="input-starting"
          placeholder="S"
          value={startSymbol}
          onChange={(e) => setStartSymbol(e.target.value)}
        />
        <FieldDescription>
          List all terminal symbols of the grammar, separated by commas
        </FieldDescription>
      </Field>

      <Accordion type="single" collapsible className="mt-4 border px-4">
        <AccordionItem value="terminals">
          <AccordionTrigger>Symbol Definitions</AccordionTrigger>
          <AccordionContent>
            <Alert variant="destructive">
              <AlertTitle>Automatic Symbol Extraction</AlertTitle>
              <AlertDescription>
                The tool will try to automatically extract terminal and
                non-terminal symbols from the production rules, but you can also
                specify them manually here if you want to. Make sure they are
                consistent with the production rules you provided.
              </AlertDescription>
            </Alert>
            <Field className="mt-4">
              <FieldLabel htmlFor="input-terminals">
                Terminal Symbols
              </FieldLabel>
              <Input
                id="input-terminals"
                placeholder="a,b,c"
                value={terminals.join(",")}
                onChange={(e) => setTerminals(e.target.value.split(","))}
              />
              <FieldDescription>
                List all terminal symbols of the grammar, separated by commas
              </FieldDescription>
            </Field>

            <Field className="mt-4">
              <FieldLabel htmlFor="input-nonterminals">
                Non Terminal Symbols
              </FieldLabel>
              <Input
                id="input-nonterminals"
                placeholder="A,B,C"
                value={nonTerminals.join(",")}
                onChange={(e) => setNonTerminals(e.target.value.split(","))}
              />
              <FieldDescription>
                List all non terminal symbols of the grammar, separated by
                commas
              </FieldDescription>
            </Field>
          </AccordionContent>
        </AccordionItem>
      </Accordion>

      <Separator className="my-8" />
    </div>
  )
}

export default CYKAlgorithmTool
