import CYKAlgorithmTool from "./tools/cyk-algorithm"

export const courses: {
  course: string
  name: string
  description: string
  tools: {
    id: string
    name: string
    description: string
    commponent: React.ComponentType
  }[]
}[] = [
  {
    course: "atfl",
    name: "Automata Theory and Formal Languages",
    description: "",
    tools: [
      {
        id: "cyk",
        name: "CYK Algorithm",
        description:
          "Algorithm to check if a string can be generated by a context-free grammar",
        commponent: CYKAlgorithmTool,
      },
    ],
  },
]

export const tools = courses.flatMap((course) =>
  course.tools.map((tool) => ({
    ...tool,
    course: course.course,
  }))
)
