import CYKAlgorithmTool from "./tools/cyk-algorithm"
import SetOperationsTool from "./tools/set-operations"

export const courses: {
  course: string
  name: string
  description: string
  tools: {
    id: string
    name: string
    description: string
    component: React.ComponentType
  }[]
}[] = [
  {
    course: "atfl",
    name: "Automata Theory and Formal Languages",
    description: "",
    tools: [
      {
        id: "cyk",
        name: "CYK Algorithm",
        description:
          "Algorithm to check if a string can be generated by a context-free grammar",
        component: CYKAlgorithmTool,
      },
    ],
  },
  {
    course: "das",
    name: "Discrete Algebraic Structures",
    description: "",
    tools: [
      {
        id: "sets",
        name: "Set Operations",
        description: "Collection of tools to perform operations on sets",
        component: SetOperationsTool,
      },
    ],
  },
]

export const tools = courses.flatMap((course) =>
  course.tools.map((tool) => ({
    ...tool,
    course: course.course,
  }))
)
